development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: yeti-finder-dev
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: yeti-finder-test
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  host: ec2-23-23-80-55.compute-1.amazonaws.com
  port: 5432
  database: dcufkd1drjus98
  username: ddnblafozgkhxy
  password: PHN-fxkA4QzwG8FlQbxy1j0itP
